import type { MissionStepDef } from '../sim/types';

export const MISSION_CONFIG = {
  droneId: 'RAKSHAAN-SAR-01',
  firmwareVersion: 'v4.2.0-AI',
  sensorSuite: ['RGB-Dual 4K', 'FLIR Thermal HD', 'Solid-State LiDAR', 'Dual RTK-GPS'],
  telemetryRateHz: 10,
};

export const MISSION_STEPS: MissionStepDef[] = [
  {
    id: 1,
    code: '01',
    title: 'Disaster Response Alert',
    shortDesc: 'Emergency siren alert triggered. Rescue teams assembling at staging base.',
    fullDesc: 'Disaster command dispatches RAKSHAAN autonomous SAR drone to scan high-risk sector. Rescue teams prepare equipment.',
    startTime: 0,
    endTime: 15,
    hudBanner: 'ALERT: EMERGENCY DISASTER RESPONSE INITIATED',
    droneMode: 'hover',
    ledColor: '#E63946',
    suggestedCamera: 'cinematic',
    pipelineStage: 'Sensors',
    explanationText: 'Disaster command activates autonomous drone mission. Sensor suite initializes thermal & optical feeds.',
  },
  {
    id: 2,
    code: '02',
    title: 'Autonomous Takeoff & Hover',
    shortDesc: 'Propellers spin up on launch pad. Ascends to 15m cruise altitude.',
    fullDesc: 'System performs pre-flight IMU calibration, prop wash kicks up spray/dust, drone ascends and stabilizes hover vector.',
    startTime: 15,
    endTime: 30,
    hudBanner: 'TAKE-OFF / ASCEND / HOVER STABILIZED AT 15M',
    droneMode: 'hover',
    ledColor: '#22D3EE',
    suggestedCamera: 'rescuer',
    pipelineStage: 'Action',
    explanationText: 'Dual RTK-GPS fixes coordinates while optical flow holds precise hover vector above emergency pad.',
  },
  {
    id: 3,
    code: '03',
    title: 'Lawnmower Grid Search',
    shortDesc: 'Executing systematic parallel lawnmower coverage pattern over hazard zone.',
    fullDesc: 'Drone flies automated search grid, mapping ground coverage in real-time cyan matrix cells.',
    startTime: 30,
    endTime: 45,
    hudBanner: 'AUTONOMOUS LAWNMOWER GRID SEARCH ACTIVE - COVERAGE MAPPING',
    droneMode: 'searching',
    ledColor: '#22D3EE',
    suggestedCamera: 'chase',
    pipelineStage: 'Sensors',
    explanationText: 'Coverage map dynamically fills as dual sensors sweep 60-degree FOV terrain footprint.',
  },
  {
    id: 4,
    code: '04',
    title: 'RGB Computer Vision Detection',
    shortDesc: 'YOLOv8 Edge AI identifies human targets, vehicles, and structural hazards.',
    fullDesc: 'Optical camera tracks human motion trails, bounding box overlays with confidence scores (88%-96%).',
    startTime: 45,
    endTime: 60,
    hudBanner: 'AI DETECTION: HUMAN TARGET S-01 LOCATED [RGB CONFIDENCE 94.2%]',
    droneMode: 'tracking',
    ledColor: '#22C55E',
    suggestedCamera: 'fpv',
    pipelineStage: 'Perception',
    explanationText: 'Edge NPU detects human silhouette through visual spectrum pattern matching and motion optical flow.',
  },
  {
    id: 5,
    code: '05',
    title: 'Thermal FLIR Confirmation',
    shortDesc: 'Gimbal lowers, switching to FLIR thermal camera to verify body heat signature.',
    fullDesc: 'Heat signature (35.2°C - 37.2°C) confirms human life sign amidst cold water/rubble background.',
    startTime: 60,
    endTime: 75,
    hudBanner: 'SENSOR FUSION: RGB + THERMAL FLIR VERIFIED [FUSION SCORE 98.6%]',
    droneMode: 'tracking',
    ledColor: '#22C55E',
    suggestedCamera: 'thermal',
    pipelineStage: 'Sensor Fusion',
    explanationText: 'Thermal pass verifies infrared radiation signature matches living human body heat, filtering out false positives.',
  },
  {
    id: 6,
    code: '06',
    title: 'Priority Ranking Decision',
    shortDesc: 'Algorithmic ranking prioritizes victims by thermal temp, trapped state & hazard proximity.',
    fullDesc: 'Survivor S-01 assigned "#1 SAVE FIRST" badge with pulsing 3D tactical beacon indicator.',
    startTime: 75,
    endTime: 90,
    hudBanner: 'DECISION TRACE: SURVIVOR S-01 RANKED #1 SAVE FIRST (URGENCY 9.8/10)',
    droneMode: 'alert',
    ledColor: '#E63946',
    suggestedCamera: 'tactical',
    pipelineStage: 'Risk Assessment',
    explanationText: 'Urgency Matrix calculates high exposure + hypothermia trend + structural hazard proximity = Rank #1 priority.',
  },
  {
    id: 7,
    code: '07',
    title: 'Hazard Ingress & Route Block',
    shortDesc: 'Dynamic hazard expands across primary evacuation corridor. Planned route blocked.',
    fullDesc: 'Real-time hazard perimeter warning turns flight path red; risk rating exceeds safety margin.',
    startTime: 90,
    endTime: 105,
    hudBanner: 'HAZARD ALERT: PRIMARY ROUTE BLOCKED BY COLLAPSE / WATER SURGE',
    droneMode: 'replanning',
    ledColor: '#FACC15',
    suggestedCamera: 'tactical',
    pipelineStage: 'Risk Assessment',
    explanationText: 'Sensors detect rising hazard boundary blocking direct line of sight. Route risk score spikes to CRITICAL.',
  },
  {
    id: 8,
    code: '08',
    title: 'A* Alternate Path Replanning',
    shortDesc: 'Edge AI recalculates safe navigation vector avoiding active hazard polygons.',
    fullDesc: 'Old route fades; new optimal green path draws in real-time: "Replanned: +42 m, -68% risk".',
    startTime: 105,
    endTime: 120,
    hudBanner: 'REPLANNED: SAFE ALTERNATE ROUTE GENERATED [+42M, -68% RISK]',
    droneMode: 'replanning',
    ledColor: '#FACC15',
    suggestedCamera: 'tactical',
    pipelineStage: 'Mission Intelligence',
    explanationText: '3D A* Path Planner computes cost surface, choosing ridge clearance to bypass hazard zone safely.',
  },
  {
    id: 9,
    code: '09',
    title: 'GPS & Comm Link Resilience',
    shortDesc: 'Simulating signal dropouts. Visual-Inertial Odometry & Edge AI keep drone operational.',
    fullDesc: 'GPS loss triggers IMU + LiDAR localization ( uncertainty ellipse shown ). Comm loss queues telemetry packets locally.',
    startTime: 120,
    endTime: 135,
    hudBanner: 'FAILSAFE RESILIENCE: IMU + LIDAR LOCALIZATION ENGAGED (GPS/COMM RESILIENT)',
    droneMode: 'failsafe',
    ledColor: '#FACC15',
    suggestedCamera: 'lidar',
    pipelineStage: 'Action',
    explanationText: 'When GPS/comm degrade, Visual-Inertial Odometry prevents drift while local Edge AI maintains full autonomy.',
  },
  {
    id: 10,
    code: '10',
    title: 'Autonomous Target Orbit & Dispatch',
    shortDesc: 'Drone orbits victim, locking geo-coordinates. Nearest NDRF ground unit dispatched.',
    fullDesc: 'Target S-01 pinpointed with lat/long pin. Ground rescue team dispatched along green corridor with live ETA.',
    startTime: 135,
    endTime: 155,
    hudBanner: 'TARGET INVESTIGATION: GEO-TAGGED S-01 | NDRF TEAM DISPATCHED (ETA 2.5 MINS)',
    droneMode: 'tracking',
    ledColor: '#22C55E',
    suggestedCamera: 'rescuer',
    pipelineStage: 'Action',
    explanationText: 'High-precision RTK coordinates streamed to rescue squad headset. Team advances with boat / stretcher unit.',
  },
  {
    id: 11,
    code: '11',
    title: 'Sector Coverage Completion',
    shortDesc: 'Coverage grid reaches 100%. All hazard zones mapped and verified.',
    fullDesc: 'Drone completes final scan pass, confirms battery reserves and prepares Return-To-Home sequence.',
    startTime: 155,
    endTime: 168,
    hudBanner: 'GRID COVERAGE COMPLETE: 100% HAZARD SECTOR MAPPED',
    droneMode: 'searching',
    ledColor: '#22D3EE',
    suggestedCamera: 'orbit',
    pipelineStage: 'Mission Intelligence',
    explanationText: 'Full 3D volumetric spatial map synced to tactical cloud. All victims localized and categorized.',
  },
  {
    id: 12,
    code: '12',
    title: 'Return To Home & Mission Summary',
    shortDesc: 'Drone executes RTH touchdown on pad. Mission intelligence report generated.',
    fullDesc: 'Landing gears make contact. Complete mission report pops up with explainable decision trace & rescue metrics.',
    startTime: 168,
    endTime: 180,
    hudBanner: 'MISSION COMPLETE: RAKSHAAN RETURNED TO BASE & LANDED SAFELY',
    droneMode: 'rth',
    ledColor: '#22C55E',
    suggestedCamera: 'cinematic',
    pipelineStage: 'Action',
    explanationText: 'Autonomy mission successfully completed. 100% coverage, all victims located, zero operator interventions required.',
  },
];

export function getMissionStepForTime(t: number): MissionStepDef {
  const normT = Math.min(179.9, Math.max(0, t));
  const step = MISSION_STEPS.find((s) => normT >= s.startTime && normT < s.endTime);
  return step || MISSION_STEPS[MISSION_STEPS.length - 1];
}
